baseURL: "https://blog.tarunx.me"
languageCode: en-us
title: Tarun Blog
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hello 👋"
    Content: Welcome to my corner of the internet.
  socialIcons:
    - name: LinkedIn
      url: "https://facebook.com/"
    - name: Instagram
      url: "https://instagram.com/tarun.reddyyy"
    - name: Github
      url: "https://github.com/tarunkumar519"

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true
  
  ShowRssButtonInSectionTermList: true
  ShowCodeCopyButtons: true
  UseHugoToc: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
