baseURL: ""
languageCode: en-us
title: Tarun's Blog
theme: PaperMod

params:
  assets:
      disableFingerprinting: true
  homeInfoParams:
    Title: "Tarun Reddy"
    Content: Software Developer.Loves command line, DevOps and FOSS
  socialIcons:
    - name: LinkedIn
      url: "https://www.linkedin.com/in/tarun519"
    - name: Instagram
      url: "https://instagram.com/tarun.reddyyy"
    - name: Github
      url: "https://github.com/tarunkumar519"
    - name: RSS
      url: "https://blog.tarunx.me/index.xml"
    - name: buymeacoffee
      url: "https://buymeacoffee.com/tharunx"
  ShowFullTextinRSS: true
  comments: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true
  
  ShowRssButtonInSectionTermList: true
  ShowCodeCopyButtons: true
  ShowToc: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 30
googleAnalytics: G-X21DK6EL6Q
      
outputs:
  home:
    - HTML
    - RSS
    - JSON
 
